services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: windops_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
    volumes:
      - backend_reports:/app/backend/data/reports
      - backend_mailbox:/app/backend/data/sent_emails

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: windops_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_reports:
  backend_mailbox:
